import React,{useState} from 'react';
import {NavLink,Outlet,useNavigate,useLocation} from 'react-router-dom';
import {House,Dumbbell,Utensils,User,Shield,LogOut,Sun,Moon,Camera,Trophy,Plus,Scale} from 'lucide-react';
import {useApp} from '../context';
import {Logo,Confirm} from './ui';
const TABS=[['/','Início',House],['/treinos','Treinos',Dumbbell],['/nutricao','Nutrição',Utensils],['/perfil','Perfil',User]];
export default function Layout(){const {user,logout,theme,setTheme}=useApp();const [showLogout,setShowLogout]=useState(false);const [quick,setQuick]=useState(false);const nav=useNavigate();const location=useLocation();const initials=user?.name?.split(' ').map(x=>x[0]).slice(0,2).join('')||'?';const items=[['/','Início',House],['/treinos','Treinos',Dumbbell],['/desafios','Desafios',Trophy],['/nutricao','Nutrição',Utensils],['/perfil','Perfil',User],...(user?.is_admin?[['/admin','Admin',Shield]]:[])];return <div className="app-shell"><aside className="sidebar"><Logo/><div className="nav-label">SEU ESPAÇO</div><nav>{items.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'}><Icon size={21}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-coach"><Camera size={25}/><h3>Seu movimento,<br/>mais preciso.</h3><p>Acompanhe cada repetição.</p><button onClick={()=>nav('/camera/squat')}>Explorar câmera</button></div><div className="sidebar-bottom"><span className="avatar">{initials}</span><div><strong>{user?.name}</strong><small>{user?.is_admin?'Administrador':'Meu perfil'}</small></div><button className="icon-button" aria-label="Sair da conta" onClick={()=>setShowLogout(true)}><LogOut size={20}/></button></div></aside><div className="workspace"><header className="topbar"><span className="desktop-only">Seu espaço para evoluir</span><span className="mobile-only"><Logo/></span><div className="row"><button className="icon-button" aria-label={theme==='light'?'Ativar tema escuro':'Ativar tema claro'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={20}/>:<Sun size={20}/>}</button><button className="avatar" aria-label="Abrir perfil" onClick={()=>nav('/perfil')}>{initials}</button></div></header><main key={location.pathname}><Outlet/></main><footer className="app-footer"><span>Sua melhor versão começa agora.</span><span>Kynaro © 2026</span></footer></div><nav className="bottom-nav" aria-label="Navegação principal">
  <div className="nav-half">{TABS.slice(0,2).map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} aria-label={label} title={label}><Icon size={22}/></NavLink>)}</div>
  <button className={'nav-fab'+(quick?' open':'')} aria-label={quick?'Fechar atalhos':'Abrir atalhos'} aria-expanded={quick} onClick={()=>setQuick(!quick)}><Plus size={28} strokeWidth={2.4}/></button>
  <div className="nav-half">{TABS.slice(2).map(([to,label,Icon])=><NavLink key={to} to={to} aria-label={label} title={label}><Icon size={22}/></NavLink>)}</div>
</nav>
{quick&&<><div className="quick-backdrop" onClick={()=>setQuick(false)}/><div className="quick-sheet" role="menu">{[['/treinos/hoje','Treino de hoje','Iniciar ou continuar',Dumbbell],['/nutricao','Refeição','Registrar o que comeu',Utensils],['/desafios','Desafios','Ranking com amigos',Trophy],['/perfil?aba=Progresso','Peso','Registrar evolução',Scale],...(user?.is_admin?[['/admin','Admin','Painel do sistema',Shield]]:[])].map(([to,label,sub,Icon])=><button key={to} role="menuitem" className="quick-item" onClick={()=>{setQuick(false);nav(to)}}><span className="mo-icon"><Icon size={20}/></span><strong>{label}</strong><small>{sub}</small></button>)}</div></>}
{showLogout&&<Confirm title="Deseja sair?" action="Sair da conta" onClose={()=>setShowLogout(false)} onConfirm={()=>{logout();nav('/login')}}>Você será redirecionado para a tela de login.</Confirm>}</div>}
