import React,{useEffect,useRef,useState,useId} from 'react';
import {X,Eye,EyeOff,LoaderCircle,ChevronDown} from 'lucide-react';
import kynaroIcon from '../assets/kynaro-icon.svg';
function KIcon({size=27}){return <img src={kynaroIcon} alt="" width={size} height={size} style={{display:'block'}}/>}
export function Logo(){return <span className="logo"><span className="logo-mark"><KIcon size={22}/></span>kynaro</span>}
export function Button({children,variant='primary',busy=false,className='',...p}){return <button {...p} disabled={p.disabled||busy} className={`button ${variant} ${className}`} aria-busy={busy}>{busy&&<LoaderCircle className="spin" size={18}/>} {children}</button>}
export function Card({children,className='',...p}){return <section className={`card ${className}`} {...p}>{children}</section>}
export function Badge({children,tone=''}){return <span className={`badge ${tone}`}>{children}</span>}
export function Field({label,error,hint,type='text',...p}){const id=useId();const [show,setShow]=useState(false);return <div className="field"><label htmlFor={id}>{label}</label><div className="input-wrap"><input {...p} id={id} type={type==='password'&&show?'text':type} aria-invalid={!!error} aria-describedby={error||hint?id+'-help':undefined}/>{type==='password'&&<button type="button" className="eye" aria-label={show?'Ocultar senha':'Mostrar senha'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button>}</div>{(error||hint)&&<small id={id+'-help'} className={error?'error':'muted'}>{error||hint}</small>}</div>}
export function Select({label,options,...p}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><select id={id} {...p}>{options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select></div>}
export function Textarea({label,...p}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><textarea className="resize-none" id={id} rows={3} {...p}/></div>}
export function Tabs({items,value,onChange}){return <div className="tabs" role="tablist">{items.map((t,i)=><button key={t} role="tab" tabIndex={value===t?0:-1} onKeyDown={e=>{if(["ArrowLeft","ArrowRight","Home","End"].includes(e.key)){e.preventDefault();const n=e.key==="Home"?0:e.key==="End"?items.length-1:(i+(e.key==="ArrowRight"?1:-1)+items.length)%items.length;onChange(items[n]);e.currentTarget.parentElement.children[n].focus()}}} aria-selected={value===t} onClick={()=>onChange(t)} className={value===t?'active':''}>{t}</button>)}</div>}
export function Modal({title,children,onClose}){const ref=useRef();useEffect(()=>{const prior=document.activeElement;ref.current.showModal();return()=>prior?.focus();},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===ref.current)onClose()}} aria-label={title}><div className="modal-head"><h2>{title}</h2><button onClick={onClose} className="icon-button" aria-label="Fechar"><X/></button></div><div className="modal-body">{children}</div></dialog>}
export function Empty({icon:Icon=LoaderCircle,title,children,action}){return <div className="empty"><Icon size={40}/><h3>{title}</h3><p>{children}</p>{action}</div>}
export function Loading({label='Carregando...'}){return <div aria-busy="true" role="status"><p className="row"><LoaderCircle className="spin"/>{label}</p><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/></div>}
export function Accordion({title,children,defaultOpen=false,detail,className=''}){return <details className={`accordion ${className}`} open={defaultOpen||undefined}><summary><span>{title}</span><span className="row">{detail}<ChevronDown size={18}/></span></summary><div className="accordion-body">{children}</div></details>}
export function PageTitle({title,subtitle,action}){return <div className="page-title"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
export function Confirm({title,children,onClose,onConfirm,action='Excluir',variant='danger'}){return <Modal title={title} onClose={onClose}><p>{children}</p><div className="actions"><Button autoFocus variant="secondary" onClick={onClose}>Cancelar</Button><Button variant={variant} onClick={onConfirm}>{action}</Button></div></Modal>}
export const formatDate=s=>new Date(s+'T12:00:00').toLocaleDateString('pt-BR');
export const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export const parseMoney=s=>{const t=String(s).replace(/[^\d,.-]/g,'');return Number(t.includes(',')?t.replace(/\./g,'').replace(',','.'):t)};
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
